name: Run Bot
on:
  workflow_dispatch:  # Manual start

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        pip install python-telegram-bot==20.3 requests
        python main.py
